In [10]:
import numpy as np
list_ = [1,2,3,4,5]
array_list = np.array(list_)

In [12]:
#The List refers to a collection of various elements in a sequence, in which every element is basically an object.#
#Also, we can access these elements by their positions (index). On the other hand, an ArrayList creates an array 
#(dynamic) of the objects that can easily reduce or increase in size as and when required.
list_ = [1,2,3,4,5]
print (type(list_))

print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [14]:
for i in list_:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [15]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [16]:
# question 3
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [24]:
num_array.dtype

dtype('int64')

In [19]:

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]


In [22]:
print(type(num_list))

<class 'list'>


In [25]:
# for the variable list he data type will be list and for the arr_list the data type will be int

In [27]:
#question no 4
import numpy as np 

In [28]:
ab = ([1,5,2,6,7,5,8,5])

In [29]:
ac = np.array(ab)

In [31]:
ac.shape

(8,)

In [32]:
ac.reshape(2,4)

array([[1, 5, 2, 6],
       [7, 5, 8, 5]])

In [33]:
#5 question 


In [41]:
import numpy as np

In [44]:
ab = np.zeros(9)

In [45]:
ab.reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
# question no 6

In [47]:
import numpy as np 

In [48]:
ab = np.eye(5)

In [49]:
ab

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])